name: lencha_tt_client
description: Minimal educational VPN client
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_v2ray: ^1.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/vpn_config.json
